version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: behavior_journal_db
    environment:
      POSTGRES_USER: behavior_user
      POSTGRES_PASSWORD: behavior_pass
      POSTGRES_DB: behavior_journal
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-db.sql:/docker-entrypoint-initdb.d/02-init-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U behavior_user -d behavior_journal"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  app:
    # Use pre-built image instead of building
    # Option 1: Docker Hub
    # image: YOUR_DOCKERHUB_USERNAME/behavior-journal:latest

    # Option 2: GitHub Container Registry
    # image: ghcr.io/ktsang622/behavior-journal:latest

    # Option 3: Local image (after docker load)
    image: behavior-journal:latest

    container_name: behavior_journal_app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: behavior_journal_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
